import { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, Plus, Trash2, Globe, Upload, ExternalLink } from 'lucide-react';
import { useTargets, useCreateTarget, useBulkImport, useDeleteTarget } from '../hooks/useTargets';

export default function Targets() {
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [showAdd, setShowAdd] = useState(false);
  const [showBulk, setShowBulk] = useState(false);
  const [newDomain, setNewDomain] = useState('');
  const [bulkDomains, setBulkDomains] = useState('');
  const { data, isLoading } = useTargets({ page, search, status: statusFilter || undefined });
  const createTarget = useCreateTarget();
  const bulkImport = useBulkImport();
  const deleteTarget = useDeleteTarget();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-4"><div><h1 className="text-2xl font-bold">Targets</h1><p className="text-gray-500 text-sm mt-1">{data?.meta?.total || 0} domains tracked</p></div><div className="flex gap-3"><button onClick={() => setShowBulk(true)} className="btn-secondary flex items-center gap-2"><Upload size={16} /> Bulk Import</button><button onClick={() => setShowAdd(true)} className="btn-primary flex items-center gap-2"><Plus size={16} /> Add Target</button></div></div>
      <div className="flex items-center gap-4 flex-wrap"><div className="relative flex-1 max-w-md"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" /><input type="text" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search domains..." className="input-field pl-10" /></div><select value={statusFilter} onChange={(e) => { setStatusFilter(e.target.value); setPage(1); }} className="input-field w-auto"><option value="">All Status</option><option value="active">Active</option><option value="paused">Paused</option><option value="archived">Archived</option></select></div>
      <AnimatePresence>{showAdd && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={() => setShowAdd(false)}><motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }} className="glass p-6 w-full max-w-md" onClick={(e) => e.stopPropagation()}><h2 className="text-lg font-semibold mb-4">Add Target</h2><form onSubmit={(e) => { e.preventDefault(); if (newDomain.trim()) { createTarget.mutate({ domain: newDomain.trim() }); setNewDomain(''); setShowAdd(false); } }} className="space-y-4"><input type="text" value={newDomain} onChange={(e) => setNewDomain(e.target.value)} placeholder="example.com" className="input-field" autoFocus /><div className="flex gap-3 justify-end"><button type="button" onClick={() => setShowAdd(false)} className="btn-secondary">Cancel</button><button type="submit" className="btn-primary">Add</button></div></form></motion.div></motion.div>)}</AnimatePresence>
      <AnimatePresence>{showBulk && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={() => setShowBulk(false)}><motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }} className="glass p-6 w-full max-w-lg" onClick={(e) => e.stopPropagation()}><h2 className="text-lg font-semibold mb-4">Bulk Import Domains</h2><textarea value={bulkDomains} onChange={(e) => setBulkDomains(e.target.value)} placeholder="example.com\ntestsite.org\ndemo.io" rows={8} className="input-field font-mono text-sm" /><p className="text-xs text-gray-500 mt-2">One domain per line, up to 100 domains</p><div className="flex gap-3 justify-end mt-4"><button onClick={() => setShowBulk(false)} className="btn-secondary">Cancel</button><button onClick={() => { const domains = bulkDomains.split('\n').map(d => d.trim()).filter(Boolean); if (domains.length > 0) { bulkImport.mutate({ domains }); setBulkDomains(''); setShowBulk(false); } }} className="btn-primary" disabled={bulkImport.isPending}>{bulkImport.isPending ? 'Importing...' : 'Import'}</button></div></motion.div></motion.div>)}</AnimatePresence>
      <div className="space-y-3">{isLoading ? Array.from({ length: 5 }).map((_, i) => <div key={i} className="skeleton h-20 w-full rounded-xl" />) : data?.data?.length ? data.data.map((target: any) => (<motion.div key={target.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="glass p-4 card-hover flex items-center justify-between"><div className="flex items-center gap-4"><div className="w-10 h-10 rounded-xl bg-cyber-blue/10 flex items-center justify-center"><Globe size={20} className="text-cyber-blue" /></div><div><Link to={`/targets/${target.id}`} className="text-sm font-semibold hover:text-cyber-blue transition-colors flex items-center gap-2">{target.domain}<ExternalLink size={12} /></Link><div className="flex items-center gap-2 mt-1"><span className={`badge ${target.status === 'active' ? 'badge-success' : target.status === 'paused' ? 'badge-warning' : 'badge'}`}>{target.status}</span>{target.tags?.map((tag: string) => <span key={tag} className="badge badge-info text-[10px]">{tag}</span>)}{target._count && <span className="text-xs text-gray-500">{target._count.subdomains} subdomains · {target._count.scans} scans</span>}</div></div></div><div className="flex items-center gap-2"><button onClick={() => deleteTarget.mutate(target.id)} className="p-2 rounded-lg hover:bg-red-500/10 text-gray-500 hover:text-red-400 transition-all"><Trash2 size={16} /></button></div></motion.div>)) : <div className="text-center py-12 text-gray-500"><Globe size={48} className="mx-auto mb-4 opacity-30" /><p>No targets found</p><p className="text-sm mt-1">Add your first domain to get started</p></div>}</div>
      {data?.meta && data.meta.totalPages > 1 && (<div className="flex items-center justify-center gap-2"><button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1} className="btn-secondary text-sm">Previous</button><span className="text-sm text-gray-500 px-4">Page {page} of {data.meta.totalPages}</span><button onClick={() => setPage(p => Math.min(data.meta.totalPages, p + 1))} disabled={page === data.meta.totalPages} className="btn-secondary text-sm">Next</button></div>)}
    </div>
  );
}
